### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by samherrmann** [kiranjholla/ng-issues-repro#1]
I do not have access to a development environment right now to run your reproduction, but your setup looks like you're going through what I just went through this past week. Are you by any chance experiencing [this error](https://stackoverflow.com/questions/51850063/rootdir-is-expected-to-contain-all-source-files)? If yes, upgrade to Typescript 2.9.1.

**Comment by kiranjholla** [comment]
@samherrmann I don't believe the issue I am seeing is the same.

**Comment by samherrmann** [comment]
@kiranjholla ok I just cloned your project and played around with it. I got it to build by adding the following line to the `public_api.ts` file:

```
export * from './lib/modules/test/test.module';
```

In other words, the nesting of exports through `index.ts` files is causing the issue.

**Comment by kiranjholla** [comment]
This has been a very interesting exercise.

@samherrmann I took your advice and added the additional `export` statement. However, I was not so lucky and found that the build still failed with errors.

#### Unexpected value 'undefined' exported by the module

```
ERROR in : Unexpected value 'undefined' exported by the module 'TestModule in path/to/working-dir/dist/my-lib/my-lib.d.ts'
```
This took me quite a while to figure out, as I had other modules which seemingly were structured the same and did not have this error. I was finally able to isolate the issue to the `import` statements in the `test.module.ts` file.

Fixed this error by changing the `import`s from *directory-level* to *file-level* (see branch [fix/fix-unexpected-value-error](https://github.com/kiranjholla/ng-issue-23609-repro/tree/fix/fix-unexpected-value-error) in the repo). Again, the `index.ts` files were causing the issue.

#### Can't resolve all parameters for ɵb
Next, I got the following error.
```
ERROR in : Can't resolve all parameters for ɵb in path/to/working-dir/dist/my-lib/my-lib.d.ts: (?).
```
By this time I knew to look for more `index.ts` based imports. Fixed the issue by changing the `import`s in the `test.component.ts` file to use *file-level* imports, eschewing the `index.ts` files (see branch [fix/fix-can't-resolve-all-parameters-error](https://github.com/kiranjholla/ng-issue-23609-repro/tree/fix/fix-can't-resolve-all-parameters-error) in the repo).


While it was good to get this working finally, I still don't understand why `index.ts` files are causing such issues with AOT. What is happening within the AOT system that causes otherwise valid Typescript to go so horribly awry?

**Comment by samherrmann** [comment]
There are discussions on this topic [here](https://github.com/ng-packagr/ng-packagr/issues/195).

**Comment by kiranjholla** [comment]
@samherrmann Thanks! Will follow that conversation. 👍
